# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Duendata
email: john@duendata.com
description: > # this means to ignore newlines until "baseurl:"
  Duendata is about the appeal of stories told through changes in numbers.
baseurl: /thoughts # the subpath of your site, e.g. /blog
url: "http://duendata.com" # the base hostname & protocol for your site
twitter_username: @duendata
github_username:  duendata

# Build settings
markdown: kramdown
